scrape_configs:
  - job_name: "substrate_node_alice"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9615"]

  - job_name: "pushgateway"
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: [ "host.docker.internal:9091" ]